### ISSUE TITLE
Deve se evitar criar classes, para não repetir código e para facilitar a manutenção.

### ISSUE THREAD

**Issue by nelsonFAlmeida** [joanaclaudio/joanaclaudio.github.io#4]
https://github.com/joanaclaudio/joanaclaudio.github.io/blob/56a1d2101768f95930addfad7c1186c3379e5034/lab4/styles.css#L13

**Comment by joanaclaudio** [comment]
Obrigado pela ajuda consegui fazer todas as alterações
